// SSFS config engine — verifies drive mapping from SINGLE SOURCE OF TRUTH.
// Run: node ssfs/storage/config-engine.js
// Rule: ALL code (JS, Zig, Python, scripts) reads drive-mapping.json ONLY.
// No hard-coded drive letters anywhere else. Ever.
// On success: writes a receipt under V:\ssfs-vault\state\ (via resolver) — never mutates this json.

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const MAPPING_FILE = path.join(__dirname, '..', 'drive-mapping.json');

function loadMapping() {
  if (!fs.existsSync(MAPPING_FILE)) {
    fail(`drive-mapping.json not found at ${MAPPING_FILE}`);
  }
  try {
    return JSON.parse(fs.readFileSync(MAPPING_FILE, 'utf8'));
  } catch (err) {
    fail(`drive-mapping.json is not valid JSON: ${err.message}`);
  }
}

function driveRoot(letter) {
  return letter.endsWith('\\') ? letter : letter + '\\';
}

function getActualLabel(letter) {
  try {
    // PowerShell is reliable on this Windows setup
    const out = execSync(
      `powershell -NoProfile -Command "(Get-Volume -DriveLetter ${letter[0]} -ErrorAction SilentlyContinue).FileSystemLabel"`,
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
    ).trim();
    return out || null;
  } catch {
    return null;
  }
}

function fail(msg) {
  console.error('');
  console.error('!!! SSFS CONFIG ENGINE — HARD FAIL !!!');
  console.error(`!!! ${msg}`);
  console.error('!!! Fix drive mapping / hardware before any vault or archive I/O.');
  console.error('!!! This is the guard that prevents another unallocated-disk scare.');
  console.error('');
  process.exit(1);
}

function verify() {
  const mapping = loadMapping();
  const results = {};

  console.log('SSFS config engine — verifying drive mapping (single source of truth)');

  for (const [name, drive] of Object.entries(mapping.drives)) {
    const root = driveRoot(drive.letter);
    const present = fs.existsSync(root);
    results[name] = { present };

    const tag = drive.required ? 'REQUIRED' : 'optional';
    let status = present ? 'OK ' : 'MISSING';

    if (present && drive.label) {
      const actual = getActualLabel(drive.letter);
      results[name].expectedLabel = drive.label;
      results[name].actualLabel = actual;
      if (actual && actual !== drive.label) {
        status = 'LABEL MISMATCH';
        console.log(`  [${status}] ${drive.letter} ${name} (${tag}) — expected label "${drive.label}", got "${actual}"`);
        if (drive.required) {
          fail(`Required drive ${drive.letter} label mismatch (got "${actual}", want "${drive.label}").`);
        }
      }
    }

    console.log(`  [${status}] ${drive.letter} ${name} (${tag}) — ${drive.role}`);

    if (!present && drive.required) {
      fail(`Required drive ${drive.letter} (${name}, label ${drive.label}) is not mounted.`);
    }
  }

  // Write runtime receipt using dynamic computation from mapping (never pollutes git-tracked drive-mapping.json)
  try {
    const vaultLetter = mapping.drives.vault.letter;
    const stateSub = mapping.paths.state || 'state';
    const stateDir = path.join(vaultLetter + (vaultLetter.endsWith('\\') ? '' : '\\'), mapping.paths.vaultRoot || 'ssfs-vault', stateSub);
    if (!fs.existsSync(stateDir)) {
      fs.mkdirSync(stateDir, { recursive: true });
    }
    const receiptPath = path.join(stateDir, 'ssfs-verified.json');
    const receipt = {
      verifiedAt: new Date().toISOString(),
      mappingVersion: mapping.version,
      results,
      drives: mapping.drives,
      note: 'Generated by config-engine. All paths derived from drive-mapping.json. Receipt lives under vault state.'
    };
    fs.writeFileSync(receiptPath, JSON.stringify(receipt, null, 2) + '\n');
    console.log(`  Receipt written: ${receiptPath}`);
  } catch (e) {
    console.warn('  (warning) Could not write verification receipt:', e.message);
  }

  console.log('All required drives healthy (SSFS guard passed).');
  return mapping;
}

module.exports = { loadMapping, verify, MAPPING_FILE };

if (require.main === module) {
  verify();
}
